# Asset Pricing

* Universidad de Chile - ``Aplicaciones Financieras con Machine Learning``

* Franco Mansilla Ibáñez (www.francomansilla.com)

In [8]:
!pip install riskfolio-lib

Collecting riskfolio-lib
  Downloading Riskfolio_Lib-6.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (16 kB)
Requirement already satisfied: numpy>=1.24.0 in /usr/local/lib/python3.10/dist-packages (from riskfolio-lib) (1.26.4)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.10/dist-packages (from riskfolio-lib) (1.13.1)
Requirement already satisfied: pandas>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from riskfolio-lib) (2.1.4)
Collecting matplotlib>=3.8.0 (from riskfolio-lib)
  Downloading matplotlib-3.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Requirement already satisfied: clarabel>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from riskfolio-lib) (0.9.0)
Requirement already satisfied: cvxpy>=1.5.2 in /usr/local/lib/python3.10/dist-packages (from riskfolio-lib) (1.5.3)
Requirement already satisfied: scikit-learn>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from riskfolio-lib) (1.3.2)
Requirement already satisfied: statsmodels>=0.13.5 in /usr/local/lib/python3.10/dist-packages (from riskfolio-lib) (0.14.2)
Collecting arch>=7.0 (from riskfolio-lib)
  Downloading arch-7.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Collecting xlsxwriter>=3.1.2 (from riskfolio-lib)
  Downloading XlsxWriter-3.2.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.10/dist-packages (from riskfolio-lib) (3.3)
Requirement already satisfied: astropy>=5.1 in /usr/local/lib/python3.10/dist-packages (from riskfolio-lib) (6.1.2)
Collecting pybind11>=2.10.1 (from riskfolio-lib)
  Downloading pybind11-2.13.5-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: pyerfa>=2.0.1.1 in /usr/local/lib/python3.10/dist-packages (from astropy>=5.1->riskfolio-lib) (2.0.1.4)
Requirement already satisfied: astropy-iers-data>=0.2024.7.1.0.34.3 in /usr/local/lib/python3.10/dist-packages (from astropy>=5.1->riskfolio-lib) (0.2024.8.27.10.28.29)
Requirement already satisfied: PyYAML>=3.13 in /usr/local/lib/python3.10/dist-packages (from astropy>=5.1->riskfolio-lib) (6.0.2)
Requirement already satisfied: packaging>=19.0 in /usr/local/lib/python3.10/dist-packages (from astropy>=5.1->riskfolio-lib) (24.1)
Requirement already satisfied: osqp>=0.6.2 in /usr/local/lib/python3.10/dist-packages (from cvxpy>=1.5.2->riskfolio-lib) (0.6.7.post0)
Requirement already satisfied: ecos>=2 in /usr/local/lib/python3.10/dist-packages (from cvxpy>=1.5.2->riskfolio-lib) (2.0.14)
Requirement already satisfied: scs>=3.2.4.post1 in /usr/local/lib/python3.10/dist-packages (from cvxpy>=1.5.2->riskfolio-lib) (3.2.7)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.8.0->riskfolio-lib) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.8.0->riskfolio-lib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.8.0->riskfolio-lib) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.8.0->riskfolio-lib) (1.4.5)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.8.0->riskfolio-lib) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.8.0->riskfolio-lib) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.8.0->riskfolio-lib) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=2.0.0->riskfolio-lib) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=2.0.0->riskfolio-lib) (2024.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.3.0->riskfolio-lib) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.3.0->riskfolio-lib) (3.5.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.13.5->riskfolio-lib) (0.5.6)
Requirement already satisfied: qdldl in /usr/local/lib/python3.10/dist-packages (from osqp>=0.6.2->cvxpy>=1.5.2->riskfolio-lib) (0.1.7.post4)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.6->statsmodels>=0.13.5->riskfolio-lib) (1.16.0)
Downloading Riskfolio_Lib-6.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (295 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.2/295.2 kB 5.7 MB/s eta 0:00:00
Downloading arch-7.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (983 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 19.3 MB/s eta 0:00:00
Downloading matplotlib-3.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 80.1 MB/s eta 0:00:00
Downloading pybind11-2.13.5-py3-none-any.whl (240 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 241.0/241.0 kB 17.1 MB/s eta 0:00:00
Downloading XlsxWriter-3.2.0-py3-none-any.whl (159 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 159.9/159.9 kB 11.6 MB/s eta 0:00:00
Installing collected packages: xlsxwriter, pybind11, matplotlib, arch, riskfolio-lib
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.7.1
    Uninstalling matplotlib-3.7.1:
      Successfully uninstalled matplotlib-3.7.1
Successfully installed arch-7.0.0 matplotlib-3.9.2 pybind11-2.13.5 riskfolio-lib-6.2.3 xlsxwriter-3.2.0

In [9]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

import yfinance as yf

from scipy.linalg import sqrtm
import scipy.stats as st
import statsmodels.api as sm
import riskfolio as rp
from statsmodels.stats.correlation_tools import cov_nearest

import cvxpy as cp

import warnings
warnings.filterwarnings('ignore')

In [35]:
assets = ['JCI', 'TGT', 'CMCSA',
          'CPB', 'MO', 'APA',
          'AAPL', 'JPM', 'MSFT']  # qué empresas son?
assets.sort()

start = '2022-01-01'
end = '2024-06-30'

# Tickers of factors
factors = ['MTUM', 'QUAL', 'VLUE', 'SIZE', 'USMV']
factors.sort()

tickers = assets + factors
tickers.sort()

# Downloading data
data = yf.download(tickers, start = start, end = end)
data = data.loc[:,('Adj Close', slice(None))]
data.columns = tickers
data = data.dropna()

[*********************100%***********************]  14 of 14 completed

In [36]:
# Factor returns
X = data[factors].pct_change().dropna()
# Assets returns
Y = data[assets].pct_change().dropna()

## 1.1. Stepwise Regression

In [37]:
y = Y['MSFT']
X1 = sm.add_constant(X)

ols = sm.OLS(y, X1).fit()
print(ols.summary())
betas = ols.params

                            OLS Regression Results
==============================================================================
Dep. Variable:                   MSFT   R-squared:                       0.680
Model:                            OLS   Adj. R-squared:                  0.677
Method:                 Least Squares   F-statistic:                     262.3
Date:                Tue, 03 Sep 2024   Prob (F-statistic):          3.66e-150
Time:                        21:45:40   Log-Likelihood:                 1972.8
No. Observations:                 624   AIC:                            -3934.
Df Residuals:                     618   BIC:                            -3907.
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1.643e-05      0.000     -0.040      0.968      -0.001       0.001
MTUM          -0.0826      0.064     -1.284      0.200      -0.209       0.044
QUAL           2.0122      0.118     17.032      0.000       1.780       2.244
SIZE          -0.3494      0.145     -2.416      0.016      -0.633      -0.065
USMV           0.0169      0.110      0.153      0.878      -0.200       0.233
VLUE          -0.5516      0.111     -4.975      0.000      -0.769      -0.334
==============================================================================
Omnibus:                      147.147   Durbin-Watson:                   2.122
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2399.379
Skew:                           0.560   Prob(JB):                         0.00
Kurtosis:                      12.541   Cond. No.                         441.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [38]:
# La lista de factores que mejor explican una variable
best_factors = rp.forward_regression(X,
                                     Y['MSFT'],
                                     criterion='pvalue',
                                     threshold=0.05,
                                     verbose=False)
print(best_factors)

['QUAL', 'VLUE', 'SIZE']

In [39]:
# Betas de las Caracteristicas para cada Activo Y
step = 'Forward'
betas = rp.loadings_matrix(X=X,
                       Y=Y,
                       stepwise=step,
                       criterion='pvalue')
betas

          const      MTUM      QUAL      SIZE      USMV      VLUE
AAPL  -0.000135 -0.152734  1.658582 -0.414870  0.000000  0.000000
APA    0.000835  0.933812 -1.300437  0.741695 -0.941758  1.612301
CMCSA -0.000245 -0.246299  0.000000  0.000000  0.510891  0.705887
CPB    0.000354  0.000000 -1.020292  0.000000  1.828036  0.000000
JCI   -0.000160  0.000000  0.000000  1.009895  0.000000  0.000000
JPM    0.000532  0.000000  0.000000  0.000000  0.000000  0.948743
MO     0.000365  0.000000 -0.375456 -0.505550  0.757104  0.845132
MSFT  -0.000007  0.000000  1.936823 -0.322605  0.000000 -0.565081
TGT   -0.000477 -0.379341  0.000000  1.010196  0.617123  0.000000

Modelo Factorial de Microsoft

$$ R_{msft} = const + 1.936 \cdot Qual - 0.3226 \cdot Size - 0.5650 \cdot VLUE$$

In [40]:
# Expectativa de Retorno Factores (incluye constante)
prom_factor = sm.add_constant(X).mean().to_numpy().reshape(-1,1)
prom_factor

array([[1.00000000e+00],
       [2.41772310e-04],
       [3.87283086e-04],
       [1.37138263e-04],
       [1.76086751e-04],
       [6.48658397e-05]])

In [41]:
# Cálcula Expectativa de Retorno por Activo
ret_expectativa = betas.to_numpy() @ prom_factor
ret_expectativa

array([[ 4.13920047e-04],
       [ 5.97191663e-04],
       [-1.68718695e-04],
       [ 2.80753724e-04],
       [-2.14890120e-05],
       [ 5.93680435e-04],
       [ 3.38175934e-04],
       [ 6.62172840e-04],
       [-3.21072706e-04]])

In [42]:
# COV de Factores
cov_var_factores = sm.add_constant(X).cov().to_numpy()
cov_var_factores

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.55525431e-04, 1.29525162e-04, 1.17234239e-04,
        8.24088326e-05, 1.06802251e-04],
       [0.00000000e+00, 1.29525162e-04, 1.47777475e-04, 1.35803771e-04,
        9.25463260e-05, 1.20679554e-04],
       [0.00000000e+00, 1.17234239e-04, 1.35803771e-04, 1.42910144e-04,
        9.13711504e-05, 1.27871197e-04],
       [0.00000000e+00, 8.24088326e-05, 9.25463260e-05, 9.13711504e-05,
        7.44792579e-05, 8.33568757e-05],
       [0.00000000e+00, 1.06802251e-04, 1.20679554e-04, 1.27871197e-04,
        8.33568757e-05, 1.28690056e-04]])

In [43]:
# Calculo de Errores
errores = Y - sm.add_constant(X) @ betas.T
errores

,AAPL,APA,CMCSA,CPB,JCI,JPM,MO,MSFT,TGT
Date,,,,,,,,,
2022-01-04 00:00:00+00:00,-0.009297,0.016586,-0.016967,0.013278,0.008143,0.021069,0.011557,-0.003723,0.006314
2022-01-05 00:00:00+00:00,0.000079,-0.021768,0.003762,0.009104,0.003946,-0.012015,-0.012287,-0.002232,-0.007430
2022-01-06 00:00:00+00:00,-0.017082,0.031390,0.007320,0.025140,0.016120,0.007809,0.013383,-0.007956,0.014146
2022-01-07 00:00:00+00:00,0.014003,-0.009230,-0.011571,0.015000,-0.010511,0.006255,0.005923,0.019560,-0.000067
2022-01-10 00:00:00+00:00,0.006692,-0.019723,0.011047,-0.000499,-0.006940,-0.000584,0.012573,0.008840,-0.007436
...,...,...,...,...,...,...,...,...,...
2024-06-24 00:00:00+00:00,0.009556,0.042101,-0.009934,0.002180,0.009331,0.006907,0.006795,0.007334,0.011569
2024-06-25 00:00:00+00:00,-0.003725,-0.006126,0.007130,-0.010713,-0.011234,0.001065,0.006749,-0.006558,-0.007214
2024-06-26 00:00:00+00:00,0.021625,-0.007014,0.000190,0.037637,-0.021166,0.000561,0.002551,0.003010,0.008640
2024-06-27 00:00:00+00:00,0.006438,0.011363,0.001975,-0.018239,0.015237,0.008743,-0.020251,0.002997,-0.004416
2024-06-28 00:00:00+00:00,-0.006230,-0.010167,0.017624,-0.000443,-0.009592,0.007030,-0.006101,0.003214,0.008367

La matriz  $\Sigma_E$  es crucial en modelos de factor porque representa las incertidumbres o riesgos específicos de cada activo que no están relacionados con los movimientos del mercado más amplio o factores modelados.

$$\Sigma_E = \text{diag}(\text{Cov}(\epsilon))$$

In [44]:
# Varianza de los errores
sigma_e = np.diag(np.diag(errores.cov().to_numpy())) # Assume is diagonal
sigma_e

array([[0.00011941, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.0005829 , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.00017536, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.00014391, 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.00017955,
        0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.0001222 , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.00012532, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.00010552, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.00038522]])

$\sigma_{FM}$ cómo se espera que varíen conjuntamente los activos en un portafolio, considerando tanto las influencias comunes (factores) como las características únicas de cada activo.

$$ \sigma_{FM} = \beta \Sigma_{F} \beta^T + \Sigma_{E} $$

*	 $\sigma_{FM}$  es la matriz de covarianza de los activos basada en factores.
*	 $\beta$ es la matriz de betas de los activos con respecto a los factores.
*	 $\Sigma_{F}$  es la matriz de covarianza de los factores.
*	 $\beta^T$ es la transpuesta de la matriz de betas.
*	 $\Sigma_{E}$  es la matriz diagonal que contiene las varianzas específicas de los activos que no son explicadas por los factores.

In [45]:
# Factor Based Asset covariance matrix
sigma_fm = betas.to_numpy() @ cov_var_factores @ betas.to_numpy().T + sigma_e
sigma_fm

array([[3.16502352e-04, 1.36948651e-04, 1.09866944e-04, 1.58850148e-05,
        1.49511880e-04, 1.24090606e-04, 5.02333505e-05, 2.05608884e-04,
        1.59089122e-04],
       [1.36948651e-04, 8.55799055e-04, 1.23899712e-04, 2.23197841e-05,
        1.60556778e-04, 1.58083053e-04, 7.61391404e-05, 1.19740034e-04,
        1.55237212e-04],
       [1.09866944e-04, 1.23899712e-04, 2.70605516e-04, 3.74108048e-05,
        1.09137922e-04, 1.01630870e-04, 5.61296911e-05, 9.93812436e-05,
        1.26399812e-04],
       [1.58850148e-05, 2.23197841e-05, 3.74108048e-05, 2.01412965e-04,
        2.87519317e-05, 2.77516471e-05, 3.50100227e-05, 9.92724458e-06,
        4.74958039e-05],
       [1.49511880e-04, 1.60556778e-04, 1.09137922e-04, 2.87519317e-05,
        3.25297216e-04, 1.22517262e-04, 5.45433568e-05, 1.46098145e-04,
        1.57829108e-04],
       [1.24090606e-04, 1.58083053e-04, 1.01630870e-04, 2.77516471e-05,
        1.22517262e-04, 2.38037304e-04, 5.87412042e-05, 1.13624012e-04,
        1.32920728e-04],
       [5.02333505e-05, 7.61391404e-05, 5.61296911e-05, 3.50100227e-05,
        5.45433568e-05, 5.87412042e-05, 1.67096555e-04, 4.03979284e-05,
        6.59058194e-05],
       [2.05608884e-04, 1.19740034e-04, 9.93812436e-05, 9.92724458e-06,
        1.46098145e-04, 1.13624012e-04, 4.03979284e-05, 3.28592720e-04,
        1.51575624e-04],
       [1.59089122e-04, 1.55237212e-04, 1.26399812e-04, 4.74958039e-05,
        1.57829108e-04, 1.32920728e-04, 6.59058194e-05, 1.51575624e-04,
        5.67291009e-04]])

* Una matriz de covarianza debe ser siempre semidefinida positiva. Esto significa que no debería tener valores propios (eigenvalues) negativos, ya que estos implicarían varianzas negativas. Sin embargo, en la práctica, cuando estimamos matrices de covarianza a partir de datos reales o aplicamos operaciones matemáticas como las que involucran a los factores y betas, pueden surgir imprecisiones numéricas o estimaciones sesgadas que resultan en una matriz de covarianza que no es semidefinida positiva.

* Este método específico dentro de cov_nearest ajusta la matriz modificando los valores propios que sean negativos a cero (o un umbral mínimo pequeño)

* En otras palabras:  La matriz de covanriazan historica por construccion es semidefinida positiva. En cambio la matriz de covarianza de factores no tiene nada que garantice que sea semidefinida positiva

In [ ]:
sigma_fm = cov_nearest(sigma_fm, method='clipped') # delete negative eigenvalues
sigma_fm

In [53]:
n_obs, n_col = Y.shape

x = cp.Variable((n_col, 1))

risk = cp.quad_form(x, sigma_fm)

ret = ret_expectativa.T @ x

constraints = [cp.sum(x) == 1,
               x >= 0]

objective = cp.Minimize(risk)
problem = cp.Problem(objective, constraints)
problem.solve()

weights = pd.DataFrame(x.value, index=assets)
print(round(weights,6))

              0
AAPL   0.041354
APA    0.000177
CMCSA  0.088638
CPB    0.311346
JCI    0.042390
JPM    0.107380
MO     0.313385
MSFT   0.095331
TGT    0.000000

In [59]:
prom_activos = Y.mean().to_numpy().reshape(-1,1)
cov_var = Y.cov().to_numpy()

ret_portafolio = weights.T @ prom_activos

print('Rentabilidad Portafolio:', ret_portafolio[0])
print('Riesgo Portafolio:', (x.value.T @ cov_var @ x.value)**0.5)

Rentabilidad Portafolio: 0    0.000322
Name: 0, dtype: float64
Riesgo Portafolio: [[0.00930927]]